RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 172.28.10.0/24
RemoteIPInternalProxy 172.28.20.0/24

LogFormat "{\"ts\":\"%{%Y-%m-%dT%H:%M:%S%z}t\",\"remote_addr\":\"%a\",\"proxy_addr\":\"%{c}a\",\"xff\":\"%{X-Forwarded-For}i\",\"host\":\"%{Host}i\",\"metodo\":\"%m\",\"uri\":\"%U\",\"query\":\"%q\",\"protocolo\":\"%H\",\"status\":%>s,\"bytes\":%B,\"duracion_us\":%D,\"referer\":\"%{Referer}i\",\"user_agent\":\"%{User-Agent}i\"}" joomla_json

<VirtualHost *:80>
    ServerAdmin webmaster@umng.local
    DocumentRoot /var/www/html

    CustomLog /var/log/apache2/access.log combined
    CustomLog /var/log/apache2/joomla_access.json.log joomla_json

    ErrorLog /var/log/apache2/error.log
    LogLevel warn

    <Directory /var/www/html>
        Options -Indexes +FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>